# services/ai_service.py - OpenAI Integration for Report Generation

import os
from dotenv import load_dotenv
load_dotenv()

def generate_student_report(student_name: str, scores: list, subjects: list) -> str:
    """
    Generates AI report using OpenAI GPT.
    Falls back to template if API key not set.
    """
    api_key = os.getenv("OPENAI_API_KEY", "")

    if not api_key or api_key == "sk-your-openai-key-here":
        # Template report (no API key needed)
        avg = sum(scores) / len(scores) if scores else 0
        grade = "A+" if avg >= 90 else "A" if avg >= 80 else "B" if avg >= 70 else "C" if avg >= 60 else "D" if avg >= 40 else "F"

        report = f"""
📊 STUDENT PERFORMANCE REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━

Student Name: {student_name}
Overall Average: {avg:.1f}%
Overall Grade: {grade}

📈 Performance Summary:
The student has completed {len(scores)} assessments across {len(subjects)} subjects.

✅ Strong Areas:
{"Mathematics and Science" if avg >= 70 else "Needs improvement across subjects"}

📌 Areas for Improvement:
{"Continue maintaining current performance" if avg >= 70 else "Focus on regular practice and revision"}

💡 Recommendations:
{"Excellent work! Keep up the great performance." if avg >= 80 
 else "Good effort! A little more practice will help." if avg >= 60 
 else "Extra support and regular study sessions recommended."}

━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by AI Student Tracker
        """
        return report.strip()

    # OpenAI API call (Phase 7)
    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)
        avg = sum(scores) / len(scores) if scores else 0

        prompt = f"""
        Generate a detailed student performance report for {student_name}.
        Subjects: {', '.join(subjects)}
        Scores: {scores}
        Average: {avg:.1f}%
        
        Include: summary, strengths, weaknesses, and study recommendations.
        Keep it professional and encouraging.
        """

        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=500
        )
        return response.choices[0].message.content

    except Exception as e:
        return f"Report generation failed: {str(e)}"


def generate_study_plan(student_name: str, weak_subjects: list) -> str:
    """Generates a personalized study plan"""
    if not weak_subjects:
        return f"{student_name} is performing well in all subjects!"

    plan = f"""
📅 PERSONALIZED STUDY PLAN FOR {student_name.upper()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Focus subjects: {', '.join(weak_subjects)}

Week 1-2: Foundation Review
• Revisit basic concepts in {weak_subjects[0] if weak_subjects else 'all subjects'}
• Practice 30 minutes daily

Week 3-4: Practice & Assessment
• Solve practice problems daily
• Take weekly mini-tests

Week 5-6: Revision & Improvement
• Review weak areas
• Focus on exam-style questions

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    """
    return plan.strip()
